### ISSUE TITLE
MemLab cannot analyze heap across page reloads

### ISSUE THREAD

**Issue by applesaucesome** [facebookincubator/memlab#20]
I'm trying to use Memlab on my app that is login protected.  The login process causes a redirect to the login page and then redirects back to my app after a successful login.  This causes the error **"The page is reloaded. MemLab cannot analyze heap across page reloads. Please remove window.reload() calls or disable any reload logic."**

Are there any plans to enable Memlab to work with apps that have this login flow?

**Comment by JacksonGL** [comment]
@applesaucesome MemLab test scenario (with `action` and `back` callback) finds memory leaks by diffing heap snapshots. If the web page reloads, diffing heap snapshot doesn't make sense since browser refreshes the JS heap.

Have you tried the [`cookies`](https://facebookincubator.github.io/memlab/docs/api/interfaces/core_src.IScenario/#optional-cookies) callback?

We may be able to support start checking reload after the [`setup`](https://facebookincubator.github.io/memlab/docs/api/interfaces/core_src.IScenario/#-optional-setup-interactionscallback) call so you can do the login with reloading inside the `setup` callback.


MemLab also supports finding memory leaks based on a single heap snapshot taken manually from Chrome.
```
memlab view-heap --snapshot <path to .heapsnapshot file>
```

**Comment by applesaucesome** [comment]
@JacksonGL I'll give these alternate approaches a try, thank you!!  Also, I support the idea of being able to pick when the check starts, like you're suggesting.  I think it could be a more flexible approach for these login/redirect scenarios.
